const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const toggle=document.querySelector('.nav-toggle'),links=document.querySelector('.nav-links');
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));links?.classList.toggle('open',!open)});
document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>{links?.classList.remove('open');toggle?.setAttribute('aria-expanded','false')}));
const reveals=document.querySelectorAll('.reveal');if(reduced)reveals.forEach(x=>x.classList.add('visible'));else{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});reveals.forEach(x=>io.observe(x))}
const hotspotData={spindle:{k:'Interface 01',title:'24 mm spindle',copy:'A steel-reinforced hollow axle fits widely available outboard bottom brackets.',rows:[['Standard','24 mm'],['Shells','BSA / PF86']]},ring:{k:'Interface 02',title:'Direct-mount ring',copy:'A wide spline transfers torque with no redundant spider hardware.',rows:[['Options','44 / 48 / 50T'],['Chain','10–12 speed']]},arm:{k:'Interface 03',title:'Hollow-forged arm',copy:'Variable wall sections support sprint loads while controlling total mass.',rows:[['Lengths','160–175 mm'],['Q-factor','147 mm']]}};
document.querySelectorAll('[data-hotspot]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-hotspot]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const d=hotspotData[btn.dataset.hotspot];document.querySelector('#spec-kicker').textContent=d.k;document.querySelector('#spec-title').textContent=d.title;document.querySelector('#spec-copy').textContent=d.copy;document.querySelector('#spec-list').innerHTML=d.rows.map(r=>`<div><dt>${r[0]}</dt><dd>${r[1]}</dd></div>`).join('')}));
const viewer=document.querySelector('[data-viewer]'),product=document.querySelector('#viewer-product'),output=document.querySelector('#angle-output');let angle=0,velocity=0,lastX=0,lastT=0,dragging=false,raf=0;function render(){if(!product)return;const squash=.42+.58*Math.abs(Math.cos(angle*Math.PI/180));product.style.transform=`rotateY(${angle}deg) scaleX(${squash})`;if(output)output.value=`${Math.round(((angle%360)+360)%360)}°`}function coast(){if(reduced||dragging||Math.abs(velocity)<.02)return;angle+=velocity;velocity*=.94;render();raf=requestAnimationFrame(coast)}if(viewer){render();viewer.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastT=performance.now();velocity=0;cancelAnimationFrame(raf);viewer.setPointerCapture(e.pointerId)});viewer.addEventListener('pointermove',e=>{if(!dragging)return;const now=performance.now(),dx=e.clientX-lastX;angle+=dx*.65;velocity=dx*.65/Math.max(1,(now-lastT)/16);lastX=e.clientX;lastT=now;render()});const end=()=>{dragging=false;raf=requestAnimationFrame(coast)};viewer.addEventListener('pointerup',end);viewer.addEventListener('pointercancel',end);viewer.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();angle+=e.key==='ArrowLeft'?-12:12;velocity=0;render()}})}
const finishes={graphite:['Graphite','#292c2e'],silver:['Machined Silver','#b9bec1'],copper:['Burnt Copper','#a45231']};document.querySelectorAll('[data-finish]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-finish]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=finishes[b.dataset.finish];product?.style.setProperty('--finish',f[1]);document.querySelector('#finish-name').textContent=f[0]}));
document.querySelector('#order-form')?.addEventListener('submit',e=>{e.preventDefault();document.querySelector('#form-status').textContent='Reservation saved locally for this demo. We’ll be in touch.';e.target.querySelector('button').disabled=true});